refactor: corrected ci

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -9,26 +9,57 @@ on:
 jobs:
   build:
     runs-on: self-hosted
+    defaults:
+      run:
+        working-directory: /home/ubuntu/actions-runner/_work/E-Commerce_0/E-Commerce_0
 
     strategy:
       matrix:
         node-version: [22.x]
 
     steps:
+      - name: Stash or remove local changes
+        run: |
+          if git diff --quiet; then
+            echo "No local changes to stash."
+          else
+            echo "Stashing local changes..."
+            git stash --include-untracked || echo "Failed to stash changes. Attempting to reset..."
+            git reset --hard || exit 1
+          fi
+
       - name: Install yarn
         run: sudo npm install -g yarn
       - uses: actions/checkout@v4
+
       - name: Use Node.js ${{ matrix.node-version }}
         uses: actions/setup-node@v4
         with:
           node-version: ${{ matrix.node-version }}
           cache: "yarn"
+
       - name: Install dependencies
         run: yarn install
-      - name: Build the dist
-        run: yarn build
+
+      - name: Build the application
+        run: yarn build && sudo rm -rf build
+
+      - name: Reset the db
+        run: yarn reset-db
+
       - name: setup and restart service
         run: |
-          sudo systemctl daemon-reload
-          sudo systemctl start e-commerce-api
-          sudo systemctl enable e-commerce-api
+          cp server-script/e-commerce-api.service /etc/systemd/system/e-commerce-api.service
+          sudo systemctl daemon reload
+          sudo systemctl restart e-commerce-api.service
+
+      - name: Verify deployment
+        run: |
+          echo "Waiting for service to start..."
+          sleep 10
+          if sudo systemctl is-active --quiet homeworkai_be_staging.service; then
+            echo "Deployment successful!"
+          else
+            echo "Deployment failed!"
+            exit 1
+          fi
